event/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns = [
    path('host/', views.host_event, name='host'),
    path('view/<int:id>', views.view_event, name='view_event'),
    path('delete/<int:id>', views.delete_event, name='delete_event'),
    path('participate/<int:id>', views.participate, name='participate'),
    path('cancel/<int:id>', views.cancel_event, name='cancel_event'),
    path('checkin/<int:id>', views.checkin_event, name='checkin'),
    path('complete/<int:id>', views.complete_event, name='complete_event'),
    path('all/', views.all_events, name='all_events'),
    # path('testmail/', views.test_mail, name='test_mail')
]

eventer/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views as account_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', account_views.landing_view, name='landing_page'),
    path('admin/', admin.site.urls),
    path('organizer/', include('organizer.urls')),
    path('participant/', include('participant.urls')),
    path('event/', include('event.urls')),
    path('login/', account_views.login_view, name='login'),
    path('home/', account_views.home, name='home'),
    path('logout/', account_views.logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/urls.py
from django.urls import path
from . import views

app_name = 'organizer'

urlpatterns = [
    path('register', views.register_organizer, name='register'),
    # to follow an organizer
    path('follow/<int:id>', views.follow_organizer, name='follow_organizer'),
    path('unfollow/<int:id>', views.unfollow_organizer, name='unfollow_organizer'),
    path('view/<int:id>', views.view_organizer, name='view_organizer'),
    path('my_events/', views.my_events, name='my_events'),
    path('all/', views.all_organizers, name='all'),
]

participant/urls.py
from django.urls import path
from . import views

app_name = 'participant'

urlpatterns = [
    path('register', views.register_participant, name='register'),
    path('follow_list/', views.follow_list, name='follow_list'),
    path('participations/', views.participations, name='participations'),
]

templates/navbar/all_events_navlink.html
{% extends 'navbar/nav_link_base.html' %}
{% block nav_link %}
{% url 'event:all_events' %}
{% endblock %}
{% block nav_link_name %} All Events {% endblock %}

templates/navbar/all_organizers_navlink.html
{% extends 'navbar/nav_link_base.html' %}

{% block nav_link %}
{% url 'organizer:all' %}
{% endblock %}

{% block nav_link_name %}
All Organizers
{% endblock %}

templates/navbar/follow_list_navlink.html
{% extends 'navbar/nav_link_base.html' %}
{% block nav_link %} {% url 'participant:follow_list' %}{% endblock %}
{% block nav_link_name %} Follow List {% endblock %}

templates/navbar/home_navlink.html
{% extends 'navbar/nav_link_base.html' %}
{% block nav_link %} {% url 'home' %}{% endblock %}
{% block nav_link_name %} Home {% endblock %}

templates/navbar/host_event_navlink.html
{% extends 'navbar/nav_link_base.html' %}

{% block nav_link %}
{% url 'event:host' %}
{% endblock %}

{% block nav_link_name %}
Host an event
{% endblock %}

templates/navbar/login_navlink.html
{% extends 'navbar/nav_link_base.html' %}

{% block nav_link %}
{% url 'login' %}
{% endblock %}

{% block nav_link_name %}
Login
{% endblock %}

templates/navbar/logout_navlink.html
{% extends 'navbar/nav_link_base.html' %}
{% block nav_link %} {% url 'logout' %}{% endblock %}
{% block nav_link_name %} Logout {% endblock %}

templates/navbar/my_events_navlink.html
{% extends 'navbar/nav_link_base.html' %}

{% block nav_link %}
{% url 'organizer:my_events' %}
{% endblock %}

{% block nav_link_name %}
My Events
{% endblock %}

templates/navbar/nav_link_base.html
<li class="nav-item">
    <a href="{% block nav_link %}{% endblock %}" class="nav-link">{% block nav_link_name %}{% endblock %}</a>
</li>

templates/navbar/participations_navlink.html
{% extends 'navbar/nav_link_base.html' %}
{% block nav_link %}
{% url 'participant:participations' %}
{% endblock %}
{% block nav_link_name %} Participations {% endblock %}

templates/navbar/register_as_organizer_navlink.html
{% extends 'navbar/nav_link_base.html' %}

{% block nav_link %}
{% url 'organizer:register' %}
{% endblock %}

{% block nav_link_name %}
Register as Organizer
{% endblock %}

templates/navbar/register_as_participant_navlink.html
{% extends 'navbar/nav_link_base.html' %}

{% block nav_link %}
{% url 'participant:register' %}
{% endblock %}

{% block nav_link_name %}
Register as Participant
{% endblock %}